on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

# Set default permissions as read only.
permissions: read-all

name: Go
jobs:

 code-check:
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Just compile
      run: |
        go build ./...
    - name: staticcheck.io
      if: startsWith(matrix.go-version, '1.23')
      uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2024.1.1"
        install-go: false
        cache-key: ${{ matrix.go }}
